### ISSUE TITLE
How can I access the nested array?

### ISSUE THREAD

**Issue by neenekrasov** [jupe/mongoose-query#101]
You guys are really cool, I love your product.

Tell me how I can refer to the nested object

 {
 "id": "17id",
    "text": "year",
    "done": true,
    "one":[{
        "test": "good"
    }]
 }

These constructions do not work ((

q={"one":[{"test":"good"}]}
q={"one":{"test":"good"}}
q={"one.test":"good"}

**Comment by jupe** [comment]
did you get it work, @neenekrasov ?
