### ISSUE TITLE
When filtering results with key={gr}number lib thinks number is a date

### ISSUE THREAD

**Issue by orsiemilio** [jupe/mongoose-query#22]
It seems that the date format is not proper checked. 
I think you should specify some date format.. so dates are for example YYYY/MM/DD.
The strings that does not match.. check if are number.
I wish you good luck :)

**Comment by jupe** [comment]
good catch. There might be something wrong when check date as a string:
https://github.com/jupe/mongoose-query/blob/master/lib/tools.js#L45. Have to add some more tests and fix it.
