### ISSUE TITLE
oid not working

### ISSUE THREAD

**Issue by esalu** [jupe/mongoose-query#79]
`oid` converted not working (with mongoose 5.5.X)... this feature was remove [here](https://github.com/jupe/mongoose-query/pull/27/commits/42b8982de82f46be431f6344a1f7b8540b0357dd?file-filters%5B%5D=.js&owned-by%5B%5D=#diff-2af4cc3a57766dfd5b392d17218d8f1cL222)... why? ;(

try with this data:

`t=aggregate&q=[{"$match":{"fieldName":"oid:XXXXXXXXX"}}]`

**Comment by jupe** [comment]
fix is coming. Have you chance to double test before release ?

**Comment by esalu** [comment]
![image](https://user-images.githubusercontent.com/2507814/59781739-ccc73a80-9292-11e9-9b74-0b9ec7a9348a.png)
