### ISSUE TITLE
$geoNear, $near, and $nearSphere are not allowed in this context

### ISSUE THREAD

**Issue by esalu** [jupe/mongoose-query#99]
Use the count method instead of the countDocuments method

https://stackoverflow.com/questions/59186475/mongoose-geonear-near-and-nearsphere-are-not-allowed-in-this-context

Use:
```
t: 'count',
q: '{
  "location": {
    "$nearSphere": {
      "$geometry": {
        "type": "Point",
        "coordinates": [LNG,LAT]
      },
      "$maxDistance": 2000
    }
  }
}'
```

**Comment by jupe** [comment]
count mongoose method is obsoleted, see: https://mongoosejs.com/docs/api/model.html#model_Model.count. Did you mean that countDocuments api wont work with this kind of query ? it sounds more like bug in mongoose or mongodb. Could you explain a bit more?

**Comment by jupe** [comment]
@esalu still issue or did it resolves somehow ? I'll close this issue unless more details are given.
